// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	Nickname string `json:"nickname"`
	Password string `json:"password"`
}

type NewUser struct {
	Email     string `json:"email"`
	Password  string `json:"password"`
	Nickname  string `json:"nickname"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type Tokens struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type User struct {
	ID        string   `json:"id"`
	Nickname  string   `json:"nickname"`
	Firstname string   `json:"firstname"`
	Lastname  string   `json:"lastname"`
	Email     string   `json:"email"`
	Role      string   `json:"role"`
	Groups    []string `json:"groups"`
}
